### ISSUE TITLE
Ignorance towards previous developments for MUSE?

### ISSUE THREAD

**Issue by Knusper** [ismaelpessa/PyMUSE#55]
I saw your paper announcing PyMUSE today on arXiv and leaves me a bit baffled.

https://arxiv.org/abs/1803.05005

 The MPDAF - MUSE Python data analysis framework - package (and, in LSDCat or qtClassify in the context of source detection) are python libraries developed with exactly the goals in mind that you want to address with your software.  Diversity is of course good, and independent approaches might find different, sometimes better, solutions for common problems.

However, not acknowledging our efforts seems a bit ignorant to me, and defies good academic practice.

MPDAF: http://ascl.net/code/v/1536
LSDCat: https://ascl.net/1612.002
qtClassify: https://ascl.net/1703.011

**Comment by ismaelpessa** [comment]
Thanks for the message. We have now updated the manuscript (both, in the arxiv and the submission to the ADASS proceedings) and added a line referencing MPDAF package for completeness.

**Comment by Knusper** [comment]
Hello,  thank you for referencing MPDAF.  I have to say I am not involved with MPDAF, and I am only a user.  I also will try out and recommend your software to others using with MUSE data.

I apologize if my wording "ignorant" was a bit  strong. It would have been better to send a private email instead of opening a bug here and commenting on VoxCharta.  I am truly sorry, and  I want to express again that I think diversity is good, and that your developments surely are important for people working with MUSE data.
