### ISSUE TITLE
ImportError: cannot import name name_from_coord

### ISSUE THREAD

**Issue by pziphi** [ismaelpessa/PyMUSE#56]
Hi...
I am using Fedora 26 and installed PyMUSE with pip install.  When I am trying to initialize, I am facing the issue:

>>> from PyMUSE.musecube import MuseCube
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/PyMUSE/musecube.py", line 20, in <module>
ImportError: cannot import name name_from_coord
>>> 

Could you help me overcome this issue by giving a solution please?
Thank you.

**Comment by ismaelpessa** [comment]
Hi!
I think that error may raise because you installed linetools using pip. If this is the case, please remove that installation and re-install directly from https://github.com/linetools/linetools (the version currently available in pip is outdated).
Please let me know if this solves your problem

**Comment by pziphi** [comment]
Hi!
Yes, reinstalling linetools worked.
Thank you for the quick reply.  :)
